# Generated by Django 3.0.7 on 2020-06-06 16:35

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='Title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
