# Generated by Django 3.0.7 on 2020-06-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200606_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
