# Generated by Django 3.0.7 on 2020-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200607_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='sort',
            field=models.IntegerField(default=1),
        ),
    ]
