# Generated by Django 3.0.7 on 2020-06-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='account_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='discord_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password_reset',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password_reset_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='socialclub_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='verified_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='verify_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='verify_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
