# Generated by Django 3.0.7 on 2020-06-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_auto_20200618_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AntwortenModel',
            new_name='Antworten',
        ),
        migrations.RenameModel(
            old_name='CharacterModel',
            new_name='Character',
        ),
        migrations.RenameModel(
            old_name='FragebogenModel',
            new_name='Fragebogen',
        ),
        migrations.RenameModel(
            old_name='FragebogenFragenModel',
            new_name='FragebogenFragen',
        ),
        migrations.RenameModel(
            old_name='FragenModel',
            new_name='Fragen',
        ),
        migrations.RenameModel(
            old_name='RightsModel',
            new_name='Rights',
        ),
        migrations.RenameModel(
            old_name='RoleRightsModel',
            new_name='RoleRights',
        ),
       migrations.RenameModel(
            old_name='RolesModel',
            new_name='Roles',
        ),
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='UserBanModel',
            new_name='UserBan',
        ),
        migrations.RenameModel(
            old_name='UserCharacterModel',
            new_name='UserCharacter',
        ),
        migrations.RenameModel(
            old_name='UserNotesModel',
            new_name='UserNotes',
        ),
        migrations.RenameModel(
            old_name='UserRolesModel',
            new_name='UserRoles',
        ),
    ]
