# Generated by Django 3.0.7 on 2020-06-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0003_auto_20200618_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='keiner', max_length=10),
            preserve_default=False,
        ),
    ]
