# Generated by Django 3.0.7 on 2020-06-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0005_auto_20200618_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
