# Generated by Django 3.0.7 on 2020-06-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0007_user_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
