# Generated by Django 3.0.7 on 2020-06-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0008_auto_20200624_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=50),
        ),
    ]
